# 模型相关参数
# CUDA_VISIBLE_DEVICES=5 python deepthulac/seg/train.py --config_path=deepthulac/seg/configs/seg/punc.yaml
pretrained_bert_model: /data03/private/chengzhili/pretrain/output/2023-06-09_21-23-00/save
heads:
  - punc
seg_labels:
  - B
  - M
  - E
  - S
punc_labels:
  - B
  - M
  - E
  - S
head_config:
  use_crf: False # 对于不完全标签的训练，不能用crf
  layers_num: 1

# 训练相关参数
saved_path: output/punc
learning_rate: 1.0e-05
# learning_rate: 1.0e-07 # 1.0e-08
warmup_steps: 0
weight_decay: 0.01
clip_grad: 5

batch_size: 32

# 训练数据
train_datasets:
  punc_baidubaike0rs:
    dir: data
    repeat_times: 1
dev_datasets:
  seg_pku:
    dir: data
  seg_msr:
    dir: data
  #seg_ours:
  #  dir: data
part_data: False #True
