# 模型相关参数
pretrained_bert_model: custom_pretrained
heads:
  - seg
  - punc
seg_labels:
  - B
  - M
  - E
  - S
punc_labels:
  - B
  - M
  - E
  - S
head_config:
  use_crf: False # 对于不完全标签的训练，不能用crf
  layers_num: 1

# 训练相关
saved_path: output/punc_dict
learning_rate: 1.0e-07
# warmup_steps: 0
weight_decay: 0.01
clip_grad: 5

batch_size: 32

train_datasets:
  punc_baidubaike0rs:
    dir: data
  dict_wantwords:
    dir: data
dev_datasets:
  seg_ours:
    dir: data
part_data: False
