# CUDA_VISIBLE_DEVICES=0 python deepthulac/seg/train.py --config_path=deepthulac/seg/configs/pos/pos.yaml
# 模型相关参数
pretrained_bert_model: /data03/private/chengzhili/pretrain/output/2023-06-09_21-23-00/save # bert-base-chinese
heads:
  - seg
  - pos
seg_labels:
  - B
  - M
  - E
  - S
pos_labels:
  - w
  - e
  - g
  - o
  - mq
  - f
  - h
  - a
  - j
  - id
  - k
  - v
  - c
  - u
  - nz
  - r
  - q
  - s
  - x
  - m
  - np
  - p
  - d
  - ns
  - t
  - n
  - ni
  # - vm
  # - vd
head_config:
  use_crf: False
  layers_num: 1
  dropout: 0.1

# 训练相关参数
saved_path: output/pos
epoch_num: 1 #3 # 1
learning_rate: 1.0e-05
warmup_steps: 0.1 #2.0 # 0.1
weight_decay: 0.01
clip_grad: 5

batch_size: 32

data_strategy: shuffle_batches
# 训练数据
train_datasets:
  seg_ours:
    dir: data
    repeat_times: 1
  pos_ours:
    dir: data
    repeat_times: 1
dev_datasets:
  seg_ours:
    dir: data
    repeat_times: 1
  pos_ours:
    dir: data
    repeat_times: 1
part_data: False #False
